### PR TITLE
DEV-14825: Configure new curalate-spymemcached repository

### PR DESCRIPTION
**Pull request by jes-bz**
Refactoring finished to convert library to work in our package hierarchy and to allow it to function with the original library in scope. 
### Work still to do
- [x] upload .jar to maven repo for curalate-commons to build off of.

### CODE REVIEW

**Comment by tmcneal** [comment]
I think Sonatype's going to require you to remove the `-SNAPSHOT` suffix - but other than that LGTM.  Mind squashing the first four commits in this PR prior to merging?

**Comment by jes-bz** [comment]
Should I also change the version number to something less 9y?

**Comment by jes-bz** [comment]
Commits squashed and -SNAPSHOT dropped

**Comment by tmcneal** [comment]
:ship:

**Pull request merged**
